config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  post "/new_employee", to: "employees#create"
  
  resources :feedbacks
  root "departments#index"
  # POST employees/:employee_id/feedbacks
  resources :employees do
    resources :feedbacks, only: :create
  end
  # POST departments/:department_id/feedbacks
  resources :departments  do
    resources :feedbacks, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
class Department < ApplicationRecord
  has_one_attached :cover
  has_many :employees, dependent: :destroy
  # Polymorphic association
  has_many :receive_feedbacks, class_name: "Feedback", as: :feedbackable, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  before_create :default_avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :department, counter_cache: true
  # Self Join
  belongs_to :manager, class_name: "Employee", optional: true
  has_many :reports, class_name: "Employee", foreign_key: "manager_id", dependent: :destroy,
                     inverse_of: "manager"
  # Avatar image
  has_one_attached :avatar
  # Polymorphic association
  has_many :feedbacks, dependent: :destroy
  has_many :receive_feedbacks, class_name: "Feedback", as: :feedbackable, dependent: :destroy

  # enums
  enum :rola, { admin: 0, regular: 1 }

  private

  def default_avatar
    return if avatar.attached?

    avatar.attach(io: File.open("app/assets/images/avatar.png"), filename: "default_avatar.png")
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :employee
  belongs_to :feedbackable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :authenticate_employee!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def pundit_user
    current_employee
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[show edit update destroy]

  # GET /departments
  def index
    @departments = Department.all
  end

  # GET /departments/1
  def show
    authorize Department
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit; end

  # POST /departments
  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path, notice: "Department was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /departments/1
  def update
    if @department.update(department_params)
      redirect_to departments_path, notice: "Department was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /departments/1
  def destroy
    @department.destroy
    redirect_to departments_url, notice: "Department was successfully destroyed.",
                                 status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_department
    @department = Department.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def department_params
    params.require(:department).permit(:name, :description, :cover)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /new_employee
  def create
    @employee = Employee.new(employee_params)
    if !@employee.avatar.attached?
      @employee.avatar.attach(io: File.open("app/assets/images/avatar.png"), filename: "default_avatar.png")
    end
    if @employee.save
      redirect_to @employee.department, notice: "Employee was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /employees/1
  def update
    if @employee.update(employee_params)
      redirect_to @employee, notice: "Employee was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /employees/1
  def destroy
    @employee.destroy
    redirect_to @employee.department, notice: "Employee was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :nationality, :email, :position, :birth_date, :role, :department_id, :manager_id, :avatar, :password)
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: %i[ show edit update destroy ]

  # GET /feedbacks
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST employees/:employee_id/feedbacks
  # POST departments/:department_id/feedbacks
  def create
    if(params[:employee_id])
      feedbackable = Employee.find(params[:employee_id])
    elsif(params[:department_id])
      feedbackable = Department.find(params[:department_id])
    end
    @feedback = Feedback.new(feedback_params)
    @feedback.feedbackable = feedbackable
    @feedback.employee = current_employee

    if @feedback.save
      redirect_to @feedback.feedbackable, notice: "Feedback was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /feedbacks/1
  def update
    if @feedback.update(feedback_params)
      redirect_to @feedback, notice: "Feedback was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /feedbacks/1
  def destroy
    @feedback.destroy
    redirect_to @feedback.feedbackable, notice: "Feedback was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feedback_params
      params.require(:feedback).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <% if department.cover.attached? %>
    <div>
      <%= image_tag department.cover, alt:"Department cover" %>
    </div>
  <% end %>
  <p>
    <strong><%= department.name %></strong>
  </p>
  <p>
    <%= department.employees_count %> employees
  </p>
  <div>
    <%= link_to "Show", department %>
    <%= link_to  "Edit", edit_department_path(department) %>
    <%= button_to  "Destroy", department, method: :delete %>
  </div>
</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>
      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div style="margin-bottom:16px">
    <%= form.label :cover, style: "display: block" %>
    <%= form.file_field :cover %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Show this department", @department %> |
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/index.html.erb
<h1>Departments</h1>
<%= link_to "New department", new_department_path %>
<div id="departments">
  <% @departments.each do |department| %>
    <%= render department %>
  <% end %>
</div>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/show.html.erb
<div>
  <p>
    <strong><%= @department.name %></strong>
  </p>
  <p>
    <%= @department.description %>
  </p>
  <%= link_to  "New employee", "/employees/new" %>
</div>
<div>
  <% if @department.employees.empty? %>
    <p>No employees yet</p>
  <% end %>
</div>
<div>
  <% @department.employees.each do |employee| %>
    <%= render "employees/employee_card", employee: employee %>
  <%end%>
</div>
<h3>Feedbacks</h3>
<%= render "feedbacks/form", { feedback: Feedback.new, feedbackable: @department} %>
<div>
  <% @department.receive_feedbacks.each do |feedback|%>
    <p>By <%= feedback.employee.name %></p>
    <p><%= feedback.body %></p>
    <%= button_to "Destroy", feedback, method: :delete %>
  <%end%>
</div>

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <div>
    <% if employee.avatar.attached? %>
      <%= image_tag employee.avatar, alt: "Avatar image", style:"width: 90px" %>
    <%end%>
  </div>
  <p>
    <strong><%= employee.name %></strong>
  </p>
  <p>
    <%= employee.position %>
  </p>
  <p>
    <%= employee.department.name %>
  </p>
  <p>
    <%= employee.nationality %>
  </p>
  <p>
    <% if employee.birth_date %>
      <%= ((Time.zone.now - employee.birth_date.to_time)/1.year.seconds).floor%> years
    <%else%>
      unknow years
    <%end%>
  </p>
  <%= link_to  "Edit", edit_employee_path(employee) %>
  <%= button_to  "Destroy", employee, method: :delete %>
  <div>
    <strong>Manager:</strong>
    <% if employee.manager %>
      <%=render "employee_card", employee: employee.manager %>
    <%else%>
      No Manager
    <%end%>
  </div>
  <div>
    <strong>Reports:</strong>
    <% employee.reports.each do |report|%>
      <%=render "employee_card", employee: report %>
    <%end%>
    <% employee.reports.empty? ? "No reports" : ""%>
  </div>
  <h3>Feedbacks</h3>
  <%= render "feedbacks/form", { feedback: Feedback.new, feedbackable: employee} %>
  <div>
    <% employee.receive_feedbacks.each do |feedback|%>
      <p>By <%= feedback.employee.name %></p>
      <p><%= feedback.body %></p>
      <%= button_to "Destroy", feedback, method: :delete %>
    <%end%>
  </div>
</div>

app/views/employees/_employee_card.html.erb
<div>
  <% if employee.avatar.attached? %>
    <div>
      <%= image_tag employee.avatar, alt:"Employee avatar", style: "width:80px" %>
    </div>
  <% end %>
  <p><%= employee.name %></p>
  <p><%= employee.position %></p>
  <%= link_to  "Show", employee %>
  <%= link_to  "Edit", edit_employee_path(employee) %>
  <%= link_to  "Destroy", employee_path(employee), data: { turbo_method: :delete, confirm: "Are you sure?" } %>
</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee, url: "/new_employee", method: :post) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :nationality, style: "display: block" %>
    <%= form.text_field :nationality %>
  </div>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.text_field :position %>
  </div>
  <div>
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>
  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.number_field :role %>
  </div>
  <div>
    <%= form.label :department_id, style: "display: block" %>
    <%= form.collection_select :department_id, Department.order(:name), :id, :name%>
  </div>
  <div>
    <%= form.label :manager_id, style: "display: block" %>
    <%= form.collection_select :manager_id, employee.id ? Employee.where(" id != ? ",employee.id) : Employee.order(:name), :id, :name, include_blank: "No Manager"%>
  </div>
  <div>
    <%= form.label :avatar, style: "display: block" %>
    <%= form.file_field :avatar %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>
<%= render "form", employee: @employee %>
<br>
<div>
  <%= link_to "Back", @employee.department %>
</div>

app/views/employees/index.html.erb
<h1>Employees</h1>
<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <p>
      <%= link_to "Show this employee", employee %>
    </p>
  <% end %>
</div>
<%= link_to "New employee", new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>
<%= render "form", employee: @employee %>
<br>
<div>
  <%= link_to "Back", departments_path %>
</div>

app/views/employees/show.html.erb
<%= render @employee %>
<div>
  <%= link_to "Back", @employee.department %>
</div>

app/views/feedbacks/_feedback.html.erb
<div id="<%= dom_id feedback %>">
  <p>
    <strong>Body:</strong>
    <%= feedback.body %>
  </p>
  <p>
    <strong>Employee:</strong>
    <%= feedback.employee_id %>
  </p>
  <p>
    <strong>Feedbackable ID:</strong>
    <%= feedback.feedbackable_id %>
  </p>
  <p>
    <strong>Feedbackable Type:</strong>
    <%= feedback.feedbackable_type %>
  </p>
</div>

app/views/feedbacks/_form.html.erb
<%= form_with(model: [feedbackable, feedback]) do |form| %>
  <% if feedback.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>
      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>
  <%# <div> %>
  <%# <%= form.label :employee_id, style: "display: block" %>
  <%# <%= form.collection_select :employee_id, Employee.order(:name), :id, :name %>
  <%# </div> %>
  <div>
    <%= form.text_field :feedbackable_id, hidden: true %>
  </div>
  <div>
    <%= form.text_field :feedbackable_type, hidden: true  %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Show this feedback", @feedback %> |
  <%= link_to "Back to feedbacks", feedbacks_path %>
</div>

app/views/feedbacks/index.html.erb
<h1>Feedbacks</h1>
<div id="feedbacks">
  <% @feedbacks.each do |feedback| %>
    <%= render feedback %>
    <p>
      <%= link_to "Show this feedback", feedback %>
    </p>
  <% end %>
</div>
<%= link_to "New feedback", new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Back to feedbacks", feedbacks_path %>
</div>

app/views/feedbacks/show.html.erb
<%= render @feedback %>
<div>
  <%= link_to "Edit this feedback", edit_feedback_path(@feedback) %> |
  <%= link_to "Back to feedbacks", feedbacks_path %>
  <%= button_to "Destroy this feedback", @feedback, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OffixReloaded</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>
  <body>
    <header>
      <%= link_to root_path do%>
        <h2>OFFIX</h2>
      <%end%>
      <% if employee_signed_in? %>
        Welcome <%= current_employee.name %>
        <%= link_to  "Log out", destroy_employee_session_path, data: { turbo_method: :delete} %>
      <%end%>
    </header>
    <hr>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <hr>
    <footer>
      Codeable Cohort11 - 2023
    </footer>
  </body>
</html>
<%# rails g devise:views %>